NethServer/nethsecurity-docs

routing.rst

Static routes could be quite complex.
I'd go with a simplified documentation and exposes more info inside the UI like the meaning of various routes types.
Eventually, we can add a common usage scenario.

static routes: add basic info

---

network.rst

https://trello.com/c/T0XsS9VO/133-basic-documentation-for-alpha1

networks: describe interfaces page

---

hotspot.rst
ipsec_tunnels.rst

first import of pages for ipsec tunnels and hotspots

ipsec and hotspot doc pages

---

migration.rst

https://trello.com/c/T0XsS9VO/133-basic-documentation-for-alpha1

migration: basic info

---

install.rst

Internet connection is not needed anymore

install: fix for squashfs image

---

index.rst
install.rst
locale/it/LC_MESSAGES/nethsecurity-docs.po
reset_recovery.rst

Card: https://trello.com/c/b1ObeS6M/153-change-filesystem-to-squashfs

Add factory reset chapter

---

release_notes.rst

Get ready for the Alpha1 release
Card: https://trello.com/c/0SsoXN5P/172-release-checklist

releases_notes: add alpha1

---

openvpn_tunnels.rst

OpoenVPN tunnel: first manual page after UI release.

openvpn tunnels

---

metrics.rst
subscription.rst

subscription: add alerts chapter

---

index.rst
troubleshooting.rst

https://trello.com/c/QeMYxNCq/201-release-notes

Add troubleshooting chapter

---

dpi_filter.rst

dpi_filter: add exclusions

---

migration.rst

migration: explain UI

---

reset_recovery.rst

factory reset: describe UI

---

release_notes.rst

release_notes: add alpha2 changelog

---

storage.rst

Card: https://trello.com/c/rT9c22TX/246-release-notes-and-documentation

storage: describe partition method

---

index.rst
openvpn_roadwarrior.rst
users_databases.rst

Users database and OpenVPN Road Warrior

---

firewall.rst

Card: https://trello.com/c/rT9c22TX/246-release-notes-and-documentation

firewall: describe rules UI

---

reverse_proxy.rst

Card: https://trello.com/c/rT9c22TX/246-release-notes-and-documentation

reverse_proxy: describe UI

---

release_notes.rst

https://trello.com/c/rT9c22TX/246-release-notes-and-documentation

release_notes: beta1 changelog

---

network.rst

Card: https://trello.com/c/PYrd3n37/301-interfaces-pppoe-ipv6

network: add DHCPv6-PD

---

backup.rst

backup: add note about backup date

---

_static/custom.css

Fix background color of "Looking for..." panel.
Before this fix:
After:

Fix background color of "Looking for..." panel

---

install.rst

See https://community.nethserver.org/t/nethsecurity-beta-1-is-ready/22799/50

install: document vmware conversion

---

index.rst
snmp.rst

Card: https://trello.com/c/DGO6nvEN/122-add-snmpd-package-to-nethsecurity-image

Add snmp server configuration

---

ddns.rst
index.rst
remote_access.rst

Card: https://trello.com/c/CA7d3b8K/315-dyndns-package

Add ddns chapter

---

multiwan.rst

fix command in doc: multiwan.rst

---

threat_shield.rst

Card: https://trello.com/c/UbzjFAwP/314-threat-shield-ip-minimal-ui

threat shield: describe new page

---

nat.rst

This is a work in progress.
Things to do:
Card: https://trello.com/c/tavYHA5b/283-nat-rules-source-and-destination-netmap

nat: describe ui page and netmap

---

reverse_proxy.rst

Card: https://trello.com/c/94ZKwwjY/339-acmesh-lets-encrypt-certificate-request-failed

reverse proxy: better explain LE certificates

---

dns_dhcp.rst

See https://partner.nethesis.it/t/dhcp-e-regole-fw-su-nethsecurity-8/8408

dhcp: document multi-value options

---

firewall.rst

See https://community.nethserver.org/t/nethsecurity-zones/23024
See also https://github.com/NethServer/nethsecurity-ui/pull/204

firewall: add dmz and guests zone

---

migration.rst

Card: https://trello.com/c/8dIW7HCJ/379-migration-mwan-needs-one-policy-per-wan

migration: diver rules are not migrated

---

controller.rst
introduction.rst
release_notes.rst

New controller
Before merge, add a link to NS8 documentation.
Card: https://trello.com/c/CZeUBCkQ/390-controller-publish-ns8-package

controller: new release

---

introduction.rst
remote_access.rst

Card: https://trello.com/c/AvpCIK5s/82-ui-login-privacy-policy
Merge after: https://github.com/NethServer/nethsecurity/pull/400

ui: add privacy policy configuration

---

controller.rst
index.rst
introduction.rst
release_notes.rst

Card: https://trello.com/c/vVL6B41R/359-release-rc1

release_notes: RC1

---

controller.rst

Document how the controller will be limited in the future.

controller: add subscription limitations

---

firewall.rst
openvpn_roadwarrior.rst

some little fix I had ready from longtime

Litlle fixes and improv

---

dns_dhcp.rst

dns_dhcp.rst force dhcp option

---

release_notes.rst

release_notes: add rc2

---

backup.rst
controller.rst
dpi_filter.rst
remote_support.rst
threat_shield.rst
updates.rst
users_databases.rst

Add a banner to highlight features available only with a subscription.
Add the note in the following chapters:

Subscription banner

---

controller.rst
remote_access.rst

controller: document required port 9090

---

install.rst

install: add Windows note

---

migration.rst

migration: remove thread shield DNS

---

backup.rst

This was not documented on our manual.

backup: add customization

---

migration.rst
subscription.rst
threat_shield.rst

Changes:
- add post migration steps
- add link to existing features

migration: better explain existing limitations

---

release_notes.rst

Changelog for NethSecurity 8.0 final

release_notes: first stable release

---

release_notes.rst

release_notes: version 1.0.1

---

dns_dhcp.rst
migration.rst

write note for  dhcpleasemax and the migration behavior
https://github.com/NethServer/nethsecurity/issues/585

DHCP lease management capacity setting and migration

---

multiwan.rst

sticky option explained in multiwan

Sticky option

---

threat_shield.rst

* community blocklist section added
* Changed 'Premium' to 'Enterprise' to align it with the interface.

TS_community section added

---

remote_access.rst
users_databases.rst

users: describe extra administrators

---

migration.rst
users_databases.rst

users: explain user_bind_dn field

---

release_notes.rst
updates.rst

Releases notes for new image 1.1.0

Release 1.1.0

---

users_databases.rst

The proposed configuration should work with most Microsoft Active Directory installations.
NethServer/nethsecurity#627

users_database: fix AD suggested config

---

connections.rst
index.rst

set usage and description of  conntrack inside the documentation
https://github.com/NethServer/nethsecurity/issues/568

Add connections section to documentation

---

firewall.rst

updated source/destination section

---

dns_dhcp.rst
firewall.rst
index.rst
objects.rst

Firewall objects

---

hotspot.rst

Please review thoroughly, I have no clue on how the tone of the documentation is meant to be.
Ref:
- https://github.com/NethServer/nethsecurity/issues/635

hotspot: added custom dns docs entries

---

dpi_filter.rst
remote_support.rst
subscription.rst
threat_shield_ip.rst

Some services are now available also to Community subscriptions.

community subscription: expand supported services

---

backup.rst
subscription.rst

See https://github.com/NethServer/nethsecurity/pull/652

community subscription: add automatic backup

---

port_forward.rst

Ref:
- NethServer/nethsecurity#689

port_forward: add objects

---

migration.rst
network.rst
remote_access.rst

document usb-to-ethernet and usb-to-serial availability and usage
References:
- https://github.com/NethServer/nethsecurity/issues/711
- https://github.com/NethServer/nethsecurity/issues/710

usb-to-ethernet and usb-to-serial section

---

multiwan.rst

Ref:
- https://github.com/NethServer/nethsecurity/issues/671

multiwan: added object references to rule creation/edit

---

migration.rst

Issue NethServer/nethsecurity#703

migration: describe zone conversion

---

openvpn_roadwarrior.rst

Issue NethServer/nethsecurity#678

openvpn rw: describe dynamic range

---

remote_access.rst
reverse_proxy.rst

Issue NethServer/nethsecurity#699

certificates: describe default cert usage

---

backup.rst
release_notes.rst
updates.rst

- add release notes for new version based on OpenWrt 23.05.4
- describe how to restore packages
- improve updates page

Release notes for NethSecurity 8.2

---

dns_dhcp.rst

See https://community.nethserver.org/t/where-do-i-find-out-the-dns-settings/24302

dns: explain default behavior

---

remote_access.rst

- Added steps to reset the root password using failsafe mode.

Add reset root password

---

controller.rst

Updating documentation regarding on how `Version Checking` works and how to bypass it

controller: updated documentation for version check

---

migration.rst

Explane how to manage custom zones in NethSecurity8

Custom zones section added to migration chapter

---

install.rst

VirtualBox and Hyper-V section added.
note for logs storage when using a VM, 
a typo fixed

Improvements on Virtual Machines installation

---

remote_access.rst

Added documentation for SSH access from WAN.

Document SSH Access from WAN

---

openvpn_roadwarrior.rst
openvpn_tunnels.rst

This pull request enhances the documentation for OpenVPN Road Warrior and tunnel configurations, focusing on addressing packet fragmentation issues encountered by VPN users.

 MTU Settings for Road Warrior and Tunnel Configurations

---

controller.rst

Ref:
- https://github.com/NethServer/nethsecurity/issues/800

controller: added unit remote update section

---

port_forward.rst

Host set added to "resctrict access" section
improved readability
an error fixed

Port forward:Host set in "resctrict access" section

---

install.rst
updates.rst

NethServer/nethsecurity#816
Replaces: #121

install: document hypervisor tools

---

monitoring.rst
threat_shield_ip.rst

threat_shield: describe new options

---

migration.rst
release_notes.rst
updates.rst

Release 1.3.0 based on OpenWrt 23.05.5

changelog: add version 1.3.0

---

controller.rst

Add MaxMind license and refactor configuration section.

controller: improve configuration section

---

threat_shield_ip.rst

See https://community.nethserver.org/t/threat-shield-seems-not-working/24835/6?u=giacomo

feat(threat shield): add OpenVPN patterns

---

controller.rst
monitoring.rst
openvpn_roadwarrior.rst

Describe new features:
- latency charts
- controller 2FA
- OpenVPN connection history

New features

---

custom_openvpn_tunnel.rst
index.rst

This section explain how to load and use a custom vpn file, usually these configuration files come by a third-party VPN provider.

new custom vpn section

---

ips.rst

See https://github.com/NethServer/nethsecurity/pull/964

fix(ips): add new ns_disabled_rules syntax

---

monitoring.rst

Adding changes coming from: https://github.com/NethServer/nethsecurity/issues/900

docs: expanded monitoring section with latest changes

---

release_notes.rst

feat(release): add 1.4 changelog

---

monitoring.rst
netify_informatics.rst
requirements.txt

Netify informatics UI

---

threat_shield_dns.rst
threat_shield_ip.rst

- Add Threat shield DNS docs
- Fix Threat shield IP docs
Ref: 
- https://github.com/NethServer/nethsecurity/issues/906

feat: add threat shield dns documentation

---

firewall_rules.rst
port_forward.rst
zones_and_policies.rst

feat: describe logging limits

---

release_notes.rst

Shall we add even the perf commit? https://github.com/NethServer/nethsecurity/pull/1147
It is not tracked in project management.

feat: added release 1.5.1

---

conf.py
download.rst

The SBOM is available:
- on dev release, since 8-24.10.0-ns.1.5.1-15-g3af36fd7
- on stable relase, since 8-24.10.0-ns.1.5.2 (not released yet)

feat(download): show link to SBOM

---

index.rst
setup_wizard.rst

Ref:
- https://github.com/NethServer/nethsecurity/issues/1157

feat: add setup wizard

---

backup.rst

feat(backup): encryption alert

---

port_forward.rst

fix(port forward): explain any protocol, add gre

---

dns_dhcp.rst

feat(dhcp): non-standard custom options

---

.github/workflows/update-translations.yml
locale/README.md
locale/ai_translate.py
locale/requirements.txt

Translate to Italian using AI.
The PR does the following:
- it adds a new python script that uses GPT 4.1 to translate using OpenAI API key
- commit the changes to a temporary branch
- opens a PR to review the result
- upload an artifact to preview locally the translation

build: AI translation for IT lang

---

locale/it/LC_MESSAGES/release_notes.po

Translated by AI, just very few manual adjustments.

fix(18n): translate release_notes to italian

---

locale/it/LC_MESSAGES/reverse_proxy.po

fix(i18n): add reverse_proxy translation

---

index.rst
setup_wizard.rst

This reverts commit 1ef9d154c9f1fca513fa07d2af546022ce964466, that reverts 96a3a8755caa317b24cbcc257ee1769896b41a43 :melting_face: 
Ref:
- https://github.com/NethServer/nethsecurity/issues/1157

feat: re-add setup wizard

---

release_notes.rst

For the date of the release and the version number, can be changed, I have no opinion on that.

feat: added changelog

---

conf.py
requirements.txt

Using semver to parse the version with the new builds

fix(build): parsing correctly using semver for new versions

---

install.rst

use ns-install only the very first time, then forget it

fix(install): suggest the users to use ns-install only for first installations

---

port_forward.rst

Added exceptions for host set when used in port forwards.

Improve info about supported host sets for port forward

---

backup.rst

Download unencrypted backup button.
Better backup management in both community and subscription pages.

feat(backup): unencrypted backup button and many improvements

---

high_availability.rst

Adapt the command to the new command line interface.
Related PR: https://github.com/NethServer/nethsecurity/pull/1391

fix(ha): now lan interface name is required
